name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Spotless Check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Detekt Check
        run: ./gradlew detekt --stacktrace

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Upload JUnit test report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: app/build/test-results/**/*.xml